openapi: 3.0.3
info:
  title: Risk Service API
  version: 1.0.0
paths:
  /risk/{portfolioId}:
    get:
      summary: Get risk assessment for a portfolio
      parameters:
        - name: portfolioId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Risk assessment
          content:
            application/json:
              schema:
                $ref: ../../shared/schemas/riskAssessment.json
